# Generated by Django 5.0 on 2024-01-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('class_name', models.CharField(max_length=64, verbose_name='班级')),
                ('student_id', models.CharField(max_length=32, verbose_name='学号')),
                ('CodeForce_id', models.CharField(max_length=32, verbose_name='CodeForce账号')),
                ('AtCoder_id', models.CharField(max_length=32, verbose_name='AtCoder账号')),
                ('VJudge_id', models.CharField(max_length=32, verbose_name='VJudge账号')),
                ('NowCoder_id', models.CharField(max_length=32, verbose_name='牛客账号')),
                ('LuoGu_id', models.CharField(max_length=32, verbose_name='洛谷账号')),
                ('LeetCode_id', models.CharField(max_length=32, verbose_name='LeetCode账号')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
            ],
        ),
    ]
