# Generated by Django 5.0 on 2024-02-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_cfinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='NowCoder_id',
            new_name='NewCoder_id',
        ),
    ]
