# Generated by Django 5.0 on 2024-02-15 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_rename_nowcoder_id_studentinfo_newcoder_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='LeetCode_id',
        ),
    ]
