# Generated by Django 5.0 on 2024-02-15 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_remove_studentinfo_leetcode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=0, verbose_name='性别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='LuoGu_num',
            field=models.CharField(default=0, max_length=32, verbose_name='洛谷用户id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='NewCoder_num',
            field=models.CharField(default=0, max_length=32, verbose_name='牛客用户id'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AtCoderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AtCoder_id', models.CharField(max_length=32, verbose_name='AtCoder账号')),
                ('rank', models.SmallIntegerField(default=0, verbose_name='Rank排名')),
                ('rating', models.SmallIntegerField(default=0, verbose_name='Rank分数')),
                ('max_rating', models.SmallIntegerField(default=0, verbose_name='最高Rank分数')),
                ('Rated_Matches', models.SmallIntegerField(default=0, verbose_name='参加过的比赛场数')),
                ('Last_Competed', models.CharField(max_length=32, verbose_name='最近一次参加比赛的时间')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('name', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='app01.studentinfo', verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='LuoGuInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.SmallIntegerField(default=0, verbose_name='总做题数')),
                ('rating', models.SmallIntegerField(default=0, verbose_name='洛谷中排名')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('name', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='app01.studentinfo', verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='NewCodeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewCoder_id', models.CharField(max_length=32, verbose_name='NewCoder账号')),
                ('rating', models.SmallIntegerField(default=0, verbose_name='rating分数')),
                ('rank', models.SmallIntegerField(default=0, verbose_name='排名')),
                ('solved', models.SmallIntegerField(default=0, verbose_name='做题数')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('name', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='app01.studentinfo', verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='VJudgeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VJudge_id', models.CharField(max_length=32, verbose_name='VJudge账号')),
                ('Overall_solved', models.SmallIntegerField(default=0, verbose_name='总做题数')),
                ('last_24hours_solved', models.SmallIntegerField(default=0, verbose_name='过去一天做题数')),
                ('last_7days_solved', models.SmallIntegerField(default=0, verbose_name='过去一周做题数')),
                ('last_30days_solved', models.SmallIntegerField(default=0, verbose_name='过去一个月做题数')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('name', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='app01.studentinfo', verbose_name='姓名')),
            ],
        ),
    ]
