# Generated by Django 5.0 on 2024-02-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_luoguinfo_luogu_num_newcodeinfo_newcoder_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='luoguinfo',
            name='LuoGu_id',
            field=models.CharField(default=0, max_length=32, verbose_name='LuoGu账户'),
            preserve_default=False,
        ),
    ]
