# Generated by Django 5.0 on 2024-02-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_luoguinfo_luogu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atcoderinfo',
            name='Rated_Matches',
            field=models.CharField(max_length=32, verbose_name='参加过的比赛场数'),
        ),
        migrations.AlterField(
            model_name='atcoderinfo',
            name='max_rating',
            field=models.CharField(max_length=32, verbose_name='最高Rank分数'),
        ),
        migrations.AlterField(
            model_name='atcoderinfo',
            name='rank',
            field=models.CharField(max_length=32, verbose_name='Rank排名'),
        ),
        migrations.AlterField(
            model_name='atcoderinfo',
            name='rating',
            field=models.CharField(max_length=32, verbose_name='Rank分数'),
        ),
        migrations.AlterField(
            model_name='cfinfo',
            name='max_rating',
            field=models.CharField(max_length=32, verbose_name='最高Rank分数'),
        ),
        migrations.AlterField(
            model_name='cfinfo',
            name='rating',
            field=models.CharField(max_length=32, verbose_name='Rank分数'),
        ),
        migrations.AlterField(
            model_name='cfinfo',
            name='solved_all_time',
            field=models.CharField(max_length=32, verbose_name='总做题数'),
        ),
        migrations.AlterField(
            model_name='cfinfo',
            name='solved_last_month',
            field=models.CharField(max_length=32, verbose_name='过去一个月做题数'),
        ),
        migrations.AlterField(
            model_name='cfinfo',
            name='solved_last_year',
            field=models.CharField(max_length=32, verbose_name='过去一年做题数'),
        ),
        migrations.AlterField(
            model_name='luoguinfo',
            name='rating',
            field=models.CharField(max_length=32, verbose_name='洛谷中排名'),
        ),
        migrations.AlterField(
            model_name='luoguinfo',
            name='solved',
            field=models.CharField(max_length=32, verbose_name='总做题数'),
        ),
        migrations.AlterField(
            model_name='newcodeinfo',
            name='rank',
            field=models.CharField(max_length=32, verbose_name='排名'),
        ),
        migrations.AlterField(
            model_name='newcodeinfo',
            name='rating',
            field=models.CharField(max_length=32, verbose_name='rating分数'),
        ),
        migrations.AlterField(
            model_name='newcodeinfo',
            name='solved',
            field=models.CharField(max_length=32, verbose_name='做题数'),
        ),
        migrations.AlterField(
            model_name='vjudgeinfo',
            name='Overall_solved',
            field=models.CharField(max_length=32, verbose_name='总做题数'),
        ),
        migrations.AlterField(
            model_name='vjudgeinfo',
            name='last_24hours_solved',
            field=models.CharField(max_length=32, verbose_name='过去一天做题数'),
        ),
        migrations.AlterField(
            model_name='vjudgeinfo',
            name='last_30days_solved',
            field=models.CharField(max_length=32, verbose_name='过去一个月做题数'),
        ),
        migrations.AlterField(
            model_name='vjudgeinfo',
            name='last_7days_solved',
            field=models.CharField(max_length=32, verbose_name='过去一周做题数'),
        ),
    ]
