# Generated by Django 5.0 on 2024-02-23 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_atcodercontestinfo_cfcontestinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_solved', models.SmallIntegerField(default=0, verbose_name='cf做题数占比')),
                ('cf_rating', models.SmallIntegerField(default=0, verbose_name='cf当前分数占比')),
                ('cf_maxRating', models.SmallIntegerField(default=0, verbose_name='cf最高分数占比')),
                ('atcoder_rating', models.IntegerField(default=0, verbose_name='atcoder分数占比')),
                ('atcoder_maxRating', models.SmallIntegerField(default=0, verbose_name='atcoder最高分数占比')),
                ('newCode_rating', models.SmallIntegerField(default=0, verbose_name='newCode分数占比')),
                ('newCode_solved', models.SmallIntegerField(default=0, verbose_name='newCode做题数占比')),
                ('vJudge_solved', models.SmallIntegerField(default=0, verbose_name='vJudge做题数占比')),
                ('luogu_solved', models.SmallIntegerField(default=0, verbose_name='luogu做题数占比')),
            ],
        ),
        migrations.CreateModel(
            name='StrengthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='分数')),
                ('rank', models.IntegerField(default=1, verbose_name='排名')),
                ('name', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='app01.studentinfo', verbose_name='姓名')),
            ],
        ),
    ]
