# Generated by Django 5.0 on 2024-02-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_strengthinfo_solved_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atcoderinfo',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rank分数'),
        ),
        migrations.AlterField(
            model_name='cfinfo',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rank分数'),
        ),
        migrations.AlterField(
            model_name='luoguinfo',
            name='solved',
            field=models.IntegerField(default=0, verbose_name='总做题数'),
        ),
        migrations.AlterField(
            model_name='newcodeinfo',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rank分数'),
        ),
        migrations.AlterField(
            model_name='vjudgeinfo',
            name='Overall_solved',
            field=models.IntegerField(default=0, verbose_name='总做题数'),
        ),
    ]
