# Generated by Django 5.0 on 2024-03-06 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_newcodecontest_vjudgecontest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('solved_today', models.IntegerField(default=0, verbose_name='当天做题数')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.studentinfo', verbose_name='学生信息')),
            ],
        ),
    ]
