# Generated by Django 5.0 on 2024-03-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_studentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='用户状态'),
        ),
    ]
