# Generated by Django 5.0 on 2024-03-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_studentinfo_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='AtCoder_id',
            field=models.CharField(default='null', max_length=32, verbose_name='AtCoder账号'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='CodeForce_id',
            field=models.CharField(default='null', max_length=32, verbose_name='CodeForce账号'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='LuoGu_num',
            field=models.CharField(default='null', max_length=32, verbose_name='洛谷用户id'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='NewCoder_num',
            field=models.CharField(default='null', max_length=32, verbose_name='牛客用户id'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='VJudge_id',
            field=models.CharField(default='null', max_length=32, verbose_name='VJudge账号'),
        ),
    ]
