# Generated by Django 5.0 on 2024-03-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_alter_luoguinfo_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCodeContestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='比赛名称')),
                ('registration_time', models.CharField(max_length=128, verbose_name='报名时间')),
                ('start_time', models.CharField(max_length=128, verbose_name='比赛时间')),
                ('duration', models.CharField(max_length=32, verbose_name='比赛持续时长')),
            ],
        ),
    ]
