# Generated by Django 5.0 on 2024-03-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_nc_vj_contest_nc_vj_contestdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NC_VJ_Contest',
        ),
        migrations.DeleteModel(
            name='NC_VJ_ContestData',
        ),
    ]
