# Generated by Django 5.0 on 2024-03-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_nc_vj_contest_nc_vj_contestdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atcoderinfo',
            name='Last_Competed',
            field=models.CharField(default='——', max_length=32, verbose_name='最近一次参加比赛的时间'),
        ),
        migrations.AlterField(
            model_name='atcoderinfo',
            name='rank',
            field=models.CharField(default='——', max_length=32, verbose_name='Rank排名'),
        ),
        migrations.AlterField(
            model_name='luoguinfo',
            name='rating',
            field=models.CharField(default='——', max_length=32, verbose_name='洛谷中排名'),
        ),
        migrations.AlterField(
            model_name='newcodeinfo',
            name='rank',
            field=models.CharField(default='——', max_length=32, verbose_name='排名'),
        ),
        migrations.AlterField(
            model_name='vjudgeinfo',
            name='last_24hours_solved',
            field=models.CharField(default='0', max_length=32, verbose_name='过去一天做题数'),
        ),
        migrations.AlterField(
            model_name='vjudgeinfo',
            name='last_30days_solved',
            field=models.CharField(default='0', max_length=32, verbose_name='过去一个月做题数'),
        ),
        migrations.AlterField(
            model_name='vjudgeinfo',
            name='last_7days_solved',
            field=models.CharField(default='0', max_length=32, verbose_name='过去一周做题数'),
        ),
    ]
